baseURL = 'https://premtrans.ru/'
languageCode = 'ru-RU'
title = 'ООО "Премтранс"'
theme = 'premt' 
Copyright = '© ООО "Премтранс" 2005-{year}'
sectionPagesMenu = 'main'

[params]
    email = 'p.popugaev@premtrans.ru'
